#!/bin/bash

# Verify commitlint installation
if ! command -v commitlint &> /dev/null; then
    echo "Commitlint not found. Installing..."
    npm install --global @commitlint/cli @commitlint/config-conventional
fi

# Get the commit message from the COMMIT_EDITMSG file
commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Run commitlint on the commit message
echo "$commit_msg" | commitlint --config ./commitlint-rules/commitlint.config.js